# Stage 1: Build and Train the Model
FROM python:3.9 as model_training

WORKDIR /app

# Copy the source code for model training
COPY src/model_training.py /app/

# Install any needed packages specified in requirements.txt
COPY requirements.txt /app/
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Run the model training script
RUN python model_training.py

# Stage 2: Serve Predictions
FROM python:3.9 as serving

WORKDIR /app

# Copy the trained model from the previous stage
COPY --from=model_training /app/my_model.keras /app/

# Copy the source code for serving predictions
COPY src/main.py /app/

# Expose port 80
EXPOSE 80

# Define environmental variables
ENV NAME World

# Install any needed packages specified in requirements.txt for the serving stage
COPY requirements.txt /app/
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Copy the templates directory
COPY src/templates /app/templates

# Run the Flask application for serving predictions
CMD ["python", "main.py"]
