# Stage 1: Build and Train the Model
FROM python:3.9 AS model_training

WORKDIR /app

# Copy training script and requirements
COPY src/model_training.py /app/
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

# Train and save the model (.pkl files)
RUN python model_training.py

# Stage 2: Serve Predictions
FROM python:3.9 AS serving

WORKDIR /app

# Copy trained model and scaler from previous stage
COPY --from=model_training /app/my_model.pkl /app/
COPY --from=model_training /app/scaler.pkl /app/
COPY --from=model_training /app/knn_model.pkl /app/  

# Copy Flask app and related folders
COPY src/main.py /app/
COPY src/templates /app/templates
COPY src/statics /app/statics
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 4000

CMD ["python", "main.py"]